services:

  todo-frontend:
    build:
      context: ./todo-frontend
      dockerfile: dev.Dockerfile
    volumes:
      - ./todo-frontend:/usr/src/app
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_BACKEND_URL=http://nginx:8080/api/todos

  todo-backend:
    build:
      context: ./todo-backend
      dockerfile: dev.Dockerfile
    volumes:
      - ./todo-backend:/usr/src/app
    ports:
      - "3001:3001"
    environment:
      - REDIS_URL=redis://redis:6379
      - MONGO_URL=mongodb://mongo:3456/the_database

  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.dev.conf:ro
    ports:
      - 8080:80
    container_name: reverse-proxy
    depends_on:
      - todo-frontend

volumes:
  todo-frontend:
  todo-backend:
